### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by codylane**
Hi,

I hope this pull request doesn't get rejected because it's a huge refactor of the original code base to bring this puppet module up to speed with recent puppet changes and influxdb >= 1.x.

I hope these updates will be accepted and will prevent me from creating yet another influxdb puppet module on the forge.

Let me know if you have any questions or concerns. 

Kind Regards,
-Cody

### CODE REVIEW

**Comment by n1tr0g** [comment]
Hey Cody and thank you.

Indeed is a big PR, but I agree with you we dont need another influxdb module. I will review the changes and come back to you.

**Comment by codylane** [comment]
Yeehaw!  Glad to help my friend and thank you for reviewing.  I also hope that this addresses the most if not all of the open issues and pull requests.  

I didn't update the CHANGELOG, but I can if you'd like?

**Comment by n1tr0g** [comment]
Don't worry about the ChangeLog. I need to fully review the code anyway, so while doing that I will update the logs and the metadata files.

**Comment by codylane** [comment]
Hi there - 

I know you are probably really busy but I'm just wondering if you have any questions or concerns about my changes and if they can be merged into master?  I won't hold any hard feelings if you choose not to incorporate my changes in this pull request.

**Comment by n1tr0g** [comment]
Hi,

sorry for the delay :( As you guessed the main reason is that i didn't have time to fully review it, since its a really big change. Although you made a lot of conceptual changes I like it. For now I will merge the commits , but before releasing it to the forge I want to run more tests. I should have more time end of this week. 

thank you again for the great work you did.

**Comment by codylane** [comment]
I should also say that I'm grateful for you putting this wonderful module together. 

You are very welcome and I'm glad to hear that you liked the changes.  Please don't hesitate to reach out if you need me to clarify anything.

To hopefully put your mind at ease in terms of testing I also fixed all the unit and beaker tests and they are on tip top shape and working.  I've deployed this in my production site and it has been running for the past 20 days without issues on both Ubuntu and RedHat based operating systems.   This still doesn't mean there aren't bugs, just haven't seen anyone complain yet and that's usually a good sign.

**Pull request merged**
