### PR TITLE
more missing parameters after the refactoring

### PR DESCRIPTION
**Pull request by xaniasd**
Without the added parameters an Influxdb instance wouldn't start (after the refactoring).

### CODE REVIEW

**Comment by xaniasd** [comment]
ping @n1tr0g, anything missing in this PR?

**Comment by n1tr0g** [comment]
haha my time is missing ... Just went overseas so i was on a plane for 24h+. Will look at that tonight ...

**Comment by xaniasd** [comment]
:) no worries, I just remembered this out of the blue myself

**Comment by xaniasd** [comment]
any chance this one gets merged? Data engine configuration is dearly needed

**Pull request merged**
