### PR TITLE
Add support for influxdb 1.0.0

### PR DESCRIPTION
**Pull request by dnsmichi**
Contains all required configuration changes. One breaking change inside which is explicitly mentioned in the README.md (might need some adoption, I'm not sure about your release process :)).

This patch has been properly tested with the icinga2x-influxdb Vagrant box over here: https://github.com/Icinga/icinga-vagrant

ref #46

### CODE REVIEW

**Comment by n1tr0g** [comment]
thank you again for the PR !! Nice job

**Comment by dnsmichi** [comment]
Thank for the great module making my life more easy :) That's the least I can help out :) When I get more time I'd look into managing databases as well, currently solved via shell script after provisioning in our vagrant box.

**Comment by dhoppe** [comment]
Please publish a new release to get the support of InfluxDB 1.0.0 to the Forge.

**Comment by n1tr0g** [comment]
I will do it hopefully today, if time permitted. I need to do more testing to make sure I don't release a broken version :(

**Comment by dhoppe** [comment]
@n1tr0g Let me help you. I created several pull requests regarding Puppet lint, Rubocop and Travis CI testing. #49 #50 #51

**Pull request merged**
