### PR TITLE
fix template line breaks

### PR DESCRIPTION
**Pull request by NITEMAN**
Dangers of using -%> ;)

### CODE REVIEW

**Comment by n1tr0g** [comment]
haha tnx for that :) Looks like i need to improve on the rpsec tests :)

**Comment by NITEMAN** [comment]
Tested with 0.9.4-rc1... maybe it's time tu update the forge?

**Comment by n1tr0g** [comment]
yeah working on that right now :) I will probably release the new version today. tnx again for all the help

**Comment by NITEMAN** [comment]
Thanks to you for your work

**Pull request merged**
